### ISSUE TITLE
提示所在地区无法访问

### ISSUE THREAD

**Issue by Max-Sum** [Chion82/163-music-unlock#11]
是不是因为给了会向网易发Remote IP的问题？

**Comment by Chion82** [comment]
使用的是哪个客户端？不改hosts的话能用么？

**Comment by Max-Sum** [comment]
Surge，不能我在香港

**Comment by Max-Sum** [comment]
我想在阿里云搭自己的服务器，现在的源码好像不完整？

**Comment by Chion82** [comment]
阿里云搭不了的，因为通过域名访问80端口web，域名没有备案的话会被拦截
现在我的两台反代服务器分别在SLHK和日本，都可以正常访问网易音乐的接口，看来这个还是要看运气
Python脚本代码是完整的，需要用pip安装`flask`和`requests`两个依赖，然后用带[ngx_http_substitutions_filter_module](https://github.com/yaoweibin/ngx_http_substitutions_filter_module)模块的nginx，使用`server/nginx_conf.conf`这个配置文件就可以了。

**Comment by Chion82** [comment]
部署方法已更新到README中，请参考:)

**Comment by Chion82** [comment]
对了，检查一下`m1.music.126.net`, `m2.music.126.net`, `m3.music.126.net`是否解析成了`1.1.1.1`，境外dns会有这个问题。m1~m3都是存放音乐文件的CDN，都是一样的。这里提供几个可用的ip，可以加到hosts里面:
```
118.118.171.29
182.140.231.59
182.140.147.56
61.188.191.90
```

**Comment by Max-Sum** [comment]
我刚刚解决了。
需要在nginx里加sub_filter '"abroad":1,' '';

**Comment by Max-Sum** [comment]
python代码也有些问题，iOS客户端输出的post不是「params=xxxx」是「\r\nparams=xxxxx」。
需要这样才行
```
if 'params' in request.form.keys():
                params = request.form['params']
        else:
                params = request.form['\r\nparams']
```

**Comment by Chion82** [comment]
奇怪了，你用我的host可以正常播放音乐吗？我这边抓到的包没有\r\n，客户端更新到3.3.3

**Comment by Max-Sum** [comment]
我更新了，然后会抓到\r\n……超奇怪，莫非是Surge的问题

**Comment by Chion82** [comment]
我写的python脚本用的是python2.7，会不会跟这个有关

**Comment by Max-Sum** [comment]
我执行应该也是2.7

**Comment by Max-Sum** [comment]
我在想SSL有没有可能安装一个自签证书来解决

**Comment by Chion82** [comment]
我试过了，IOS客户端不认自签证书。现在是通过iptables直接转发tcp请求，但是就不能修改包内容了

**Comment by Max-Sum** [comment]
就是说直接转发就等于不能再配置其他HTTPS网站了（

**Comment by Max-Sum** [comment]
我去试试SNI Proxy

**Comment by Chion82** [comment]
是这样的（
不过目前发现好像就只有用户资料和用户歌单那边会用到https

**Comment by Chion82** [comment]
看了一下SNI Proxy貌似应该可以解决
对了 你用阿里云没有被拦截请求吗？

**Comment by Max-Sum** [comment]
我用了个备案了的服务器，貌似备案了就什么域名都不会拦截（

**Comment by Chion82** [comment]
还能这么玩（
嘛。。用阿里云的话确实快很多

**Comment by Max-Sum** [comment]
解决了
```
user daemon
pidfile /var/run/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

listen 115.29.77.233:443 {
    proto tls
    table https_hosts

    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
    fallback 127.0.0.1:443
}

table https_hosts {
    music.163.com 223.252.199.7:443
}
```

**Comment by Max-Sum** [comment]
其实香港才是最快的，因为我在香港（（

**Comment by Chion82** [comment]
谢谢分享
我那个香港的服务器主要是慢在python脚本调网易API那里，客户端经常就超时重试了
