### ISSUE TITLE
安卓版不能在线听付费歌曲

### ISSUE THREAD

**Issue by wen-m** [Chion82/163-music-unlock#12]
比如 work - rihanna

**Comment by Chion82** [comment]
经过网易的修补，部分付费专辑和付费歌曲已经没有方法获取到播放地址了。大部分月付费包的歌曲还能播放，比如Shake it off - Taylor Swift

**Comment by wen-m** [comment]
还是谢谢，好过全灰色

**Comment by TomatoFryEggs** [comment]
会不会哪天全封了？

**Comment by Chion82** [comment]
@TomatoFryEggs 当然是有可能的
