### ISSUE TITLE
似乎已经不能用了

### ISSUE THREAD

**Issue by wspl** [Chion82/163-music-unlock#17]
![image](https://cloud.githubusercontent.com/assets/2133311/14527797/d4582ef0-027e-11e6-904c-545450899095.png)

**Comment by Chion82** [comment]
歌曲id是多少？

**Comment by wspl** [comment]
@Chion82 水树奈奈的「深爱」，我试着换回公共服务器就行了，我是用虚拟机两天前下载 master 分支在本地自架的…刚调试了下，错误是：
![image](https://cloud.githubusercontent.com/assets/2133311/14528055/38c698bc-0280-11e6-85a5-f9c6659d0fbe.png)

**Comment by Chion82** [comment]
其实网易在昨天已经修补了API，目前这个版本的脚本已经不可用了。公共服务器使用了其他方法仍能获取到播放地址，至于具体方法在这里不方便公开，避免网易再次封API。

**Comment by jp1017** [comment]
树大招风，科技在博弈中成长

**Comment by Chion82** [comment]
@jp1017 赞同。闷声发大财

**Comment by helloyan** [comment]
ip是暴露的，网易可以通过来源分析，迟早还是会封。

**Comment by Chion82** [comment]
@helloyan 实际上公开的两个ip还要经过几台未公开的上游服务器作为跳板

**Comment by jp1017** [comment]
言多必失
:smiley_cat:
