### ISSUE TITLE
被屏蔽的歌曲不是速度非常慢就是打开失败

### ISSUE THREAD

**Issue by OscarGong** [Chion82/163-music-unlock#2]
![img_3080](https://cloud.githubusercontent.com/assets/7035787/14226546/09f802d0-f918-11e5-82a9-822970290b41.PNG)

**Comment by Chion82** [comment]
请测试一下到服务器的链路情况：
```
ping 103.27.77.201
wget 103.27.77.201/100mb.test
```
服务器所在节点SLHK最近链路情况欠佳导致反代速度慢，近期将更换服务器

**Comment by OscarGong** [comment]
清明放假在家，家里是银通网络，待放假完用联通网络再测试一下…

**Comment by Chion82** [comment]
啊。。。国内云平台因为通过域名访问80端口都需要备案，所以暂时还是换不了服务器
刚看了一下服务器的nginx log，歌曲打开非常慢的话是因为报500了，手机客户端还在不断重试。报500的话说明该歌曲完全没有可用播放资源。最近网易好像彻底删除了少部分下架歌曲，这部分歌曲就完全没办法了。

**Comment by Chion82** [comment]
已增加了一台分流服务器，请换一台试试速度如何
