### ISSUE TITLE
可否用pac来进行部署

### ISSUE THREAD

**Issue by laoyang945** [Chion82/163-music-unlock#20]
家庭内一台机器开http服务，上面放一个pac文件
pac代理将所有music.163.com的流量导向反向代理服务器
谢谢！

**Comment by Chion82** [comment]
可以。但是未越狱iPhone使用移动数据时无法使用PAC

**Comment by dlei** [comment]
how to use pac to point music.163.com to a specific ip? thought pac can only specify what proxy to use if domain match

**Comment by Chion82** [comment]
PAC代理已部署好，请看README
