### ISSUE TITLE
使用你的nginx.conf 后无法启动nginx

### ISSUE THREAD

**Issue by evindu** [Chion82/163-music-unlock#21]
无法启动 nginx

--
nginx.service - SYSV: Nginx is an HTTP(S) server, HTTP(S) reverse proxy and IMAP/POP3 proxy server
   Loaded: loaded (/etc/rc.d/init.d/nginx)
   Active: failed (Result: exit-code) since 日 2016-04-24 13:40:35 CST; 36s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5460 ExecStop=/etc/rc.d/init.d/nginx stop (code=exited, status=0/SUCCESS)
  Process: 5463 ExecStart=/etc/rc.d/init.d/nginx start (code=exited, status=1/FAILURE)
 Main PID: 4568 (code=exited, status=0/SUCCESS)

4月 24 13:40:35 VM_71_93_centos systemd[1]: Starting SYSV: Nginx is an HTTP(S) server, HTTP(S) reverse proxy and IMAP/POP3 proxy server...
4月 24 13:40:35 VM_71_93_centos nginx[5463]: Starting nginx: nginx: [emerg] "server" directive is not allowed here in /usr/local/nginx/conf/nginx.conf:1
4月 24 13:40:35 VM_71_93_centos nginx[5463]: [FAILED]
4月 24 13:40:35 VM_71_93_centos systemd[1]: nginx.service: control process exited, code=exited status=1
4月 24 13:40:35 VM_71_93_centos systemd[1]: Failed to start SYSV: Nginx is an HTTP(S) server, HTTP(S) reverse proxy and IMAP/POP3 proxy server.
4月 24 13:40:35 VM_71_93_centos systemd[1]: Unit nginx.service entered failed state.
4月 24 13:40:35 VM_71_93_centos systemd[1]: nginx.service failed.

**Comment by evindu** [comment]
搞定了

**Comment by patrick4u** [comment]
你好， 怎么搞定的啊？

**Comment by sunhai1988** [comment]
搞定了 也不说怎么搞定的  都不结贴！！！
