### ISSUE TITLE
Online server not working after PC client upgrading to v2.0.3.131777.

### ISSUE THREAD

**Issue by legendtang** [Chion82/163-music-unlock#23]
It seems the API returns raw data.

**Comment by Chion82** [comment]
It's likely that the API (`/eapi/song/enhance/player/url`), which the latest Netease Music Windows client uses, returns a fully encrypted binary response. We cannot get any requested song information from the encrypted data by now. It would be great if someone cracks the encryption.

**Comment by liverliu** [comment]
Use **origin_result.content** instead of **origin_result.text** at line 33 and 36, then the data can be decrypt by the Netease Music Client.
After that, you can download the music to local.

**Comment by Chion82** [comment]
@liverliu 直接向客户端原样返回加密的binary当然没有问题，但是这个脚本就无法获取到用户请求的歌曲ID了。另外，网易已经删除绝大部分版权音乐的旧版mp3链接，现在在API未加密的IOS端或mac客户端，即使从用户请求的歌曲ID获取到了最终的文件id，通过老方法拼接出来的mp3链接也会变成404了。新版mp3链接的拼凑规则暂未有规则可循，貌似只有调用新版API才能获取到，而目前发现的新版API都不能获取到版权音乐信息

**Comment by liverliu** [comment]
我的意思是，下载接口对所有歌曲都还是有效的，不管是被版权的，还是老接口里面404的，所以可以下载下来听，不过这应该是最后一个办法了，如果这个API也失效或者歌单接口的返回也加密了，那基本也就没救了。

**Comment by Chion82** [comment]
@liverliu 试了一下确实可行，虽然感觉可能很快也用不了了。。。用这个方法我想可以尝试改一下脚本。
闷声发大财，我先把你的评论马赛克起来:)

**Comment by Chion82** [comment]
@liverliu 尝试逆过请求param的加密串，然而因为加密函数是native的所以非常难搞，现在我只能做到直接调用加密方法，而不知道如何解密

**Comment by liverliu** [comment]
:)闷声发大财，这才是坠吼的。最近我在A站和微博上都看到好多人提供hosts，感觉还是不要太张扬好。我就基本上自己用用，只share给了几个朋友。
param码感觉基本上是不可逆的，我也尝试过逆安卓客户端，但是代码混淆了，反编译基本上就是一坨翔，没法看。
不知道你所说的调用加密方法是怎么弄的？用xposted插件hack进安卓客户端？

**Comment by Chion82** [comment]
@liverliu 目前我是用xposed来测试的。如果成功的话可以应该可以直接用`DexClassLoader`来调取apk中的方法

**Comment by liverliu** [comment]
@Chion82 我对安卓不是很熟，你如果成功了，可以私信告诉我怎么弄:)
我这几天工作忙完了去对比下新旧客户端的请求参数，有进展也告诉你

**Comment by Chion82** [comment]
@liverliu 有最新跟进了，方便留一下邮箱吗？

**Comment by liverliu** [comment]
@Chion82  shi753951@gmail.com :)

**Comment by Chion82** [comment]
solved
