### ISSUE TITLE
1.4.4 (470) 播放失败

### ISSUE THREAD

**Issue by MrBowen** [Chion82/163-music-unlock#24]
暂时未知是封了哪部分……
我改了服务器和三组子服务器的 hosts。

**Comment by MrBowen** [comment]
http://s1.music.126.net/download/osx/NeteaseMusic_1.4.3_452_web.dmg
这个应该是上一个版本的链接

**Comment by Chion82** [comment]
windows和OSX最新版本的客户端将关键API全部加密，目前还没有办法，请降回上一版本

**Comment by MrBowen** [comment]
我也发现了。
但是暂时不确定上一版本是不是我上面发布的链接。
下载地址为官网下载地址。

**Comment by Chion82** [comment]
版本号应该没有问题，我现在用的1.4.3可以正常使用

**Comment by JayFang1993** [comment]
OS X 从1.4.4降到1.4.3 可以正常，1.4.4不行。现在就是总是弹框提示升级，略烦！

**Comment by MrBowen** [comment]
看到你最近更新。
目前是可以更新最新版本了么？

**Comment by Chion82** [comment]
@MrBowen 只是增加了PAC代理方式，可以加快歌曲加载速度

**Comment by dlei** [comment]
@Chion82 咋们的PAC怎么做到的啊？
之前是用nginx做一个reverse proxy

119.29.154.223:8090 这个端口上run的是什么呢？怎么指定／eapi 就调用我们自己的python script呢？

**Comment by Chion82** [comment]
@dlei 8090上只有一个nginx的反向代理，使用的配置文件正是开源的这个nginx_conf.conf。定向的http代理跟反向代理是没有区别的。

**Comment by MrBowen** [comment]
@Chion82 刚刚尝试播放，直接无限跳过。
设置了四个 hosts，music、m1、m2、m3，没有设置 pac。

**Comment by Chion82** [comment]
@MrBowen 刚刚在调试服务器，现在再试试？

**Comment by cadmuxe** [comment]
@Chion82 我一直在听，没有断过。之前遇到无限跳过是升级了最新版，回滚之后一直没什么问题。

**Comment by cadmuxe** [comment]
@Chion82 奥，确实断掉了，无限跳过，刚才听的是已经加载的歌单。

**Comment by MrBowen** [comment]
@Chion82 依然不行……
我没有设置 pac，但是理论上应该不影响。

**Comment by Chion82** [comment]
@MrBowen @cadmuxe 都换pac吧，今天更新了版本之后之前的host不能用了。
另外现在已经兼容全平台的最新版，可以更新到1.4.4了

**Comment by MrBowen** [comment]
@Chion82 刚才删除 hosts，加入了 pac 确实可以播放了。
现在准备更新到 1.4.4 试试。
iOS 还是保持用 hosts 加上一版本的 app，测试了一下，你刚刚更新后也不行了……
iOS 加 pac 还是比较麻烦的啊……
有什么结合 surge 的好办法么？

**Comment by Chion82** [comment]
@MrBowen iOS加pac非常的简单。在连接wifi之后在wifi详情页最底下的HTTP代理选择自动，然后把PAC地址复制进去就行了

**Comment by MrBowen** [comment]
@Chion82 
这个我知道，但是非 WiFi 下那不就是废了么，对吧（每月 50 G 流量）
是要把 hosts 改到 119.29.154.223 么？

**Comment by Chion82** [comment]
@MrBowen 这个是国内的云，直接访问80端口因为没有备案会被拦截的，所以直接设置hosts不行。刚刚我把两台hosts直接转发过去了，现在应该可以直接用hosts，但是hosts的话依然很慢

**Comment by MrBowen** [comment]
恩，看到是腾讯云的主机。
测试 iOS 端已经可以了。
谢谢。
另外，你还准备更新这些到项目主页么。

**Comment by Chion82** [comment]
@MrBowen 之后会更新的
