### ISSUE TITLE
PC 端 2.0.3 无法播放所有歌曲

### ISSUE THREAD

**Issue by dfc643** [Chion82/163-music-unlock#25]
PC 端 2.0.3 无法播放所有歌曲，PC 端 2.0.1 好像没有问题。
所有没有播放过的歌曲在 2.0.3 上面会播放失败。

**Comment by Chion82** [comment]
windows端从2.0.3开始、OSX端从1.4.4开始对关键API加密，目前尚未找到破解方法，请降回旧版

**Comment by dfc643** [comment]
原来如此，谢谢
