### ISSUE TITLE
ios 怎么添加 pac 呢？

### ISSUE THREAD

**Issue by bigsma11** [Chion82/163-music-unlock#26]
你好，请问 ios 怎么添加 pac 呢？谷歌好久找不到方法，用 surge 也没找到怎么添加

**Comment by Chion82** [comment]
连接上wifi，然后在wifi详情页的最底部http代理中选择自动，URL填入pac的地址即可

**Comment by bigsma11** [comment]
恩谢谢，那就只能连 wifi 用吗？

**Comment by Chion82** [comment]
未越狱的话就只能连wifi用了 不过surge应该是可以手动写配置用pac的
