### ISSUE TITLE
安卓3.4.1 版本好像不能用了. 

### ISSUE THREAD

**Issue by wen-m** [Chion82/163-music-unlock#28]
今天刚更新安卓版本, 已经失效了, 全部变回灰色了.

**Comment by stevenzhou0825** [comment]
好象是吧，我也发现了

**Comment by Chion82** [comment]
已更新

**Comment by wen-m** [comment]
满血复活了，更新给力👍

**Comment by stevenzhou0825** [comment]
你用的是hosts还是pac，为什么我用了pac后还是不行。

**Comment by wen-m** [comment]
我用hosts 可以，在路由器里加的，安卓没有root不可以改hosts

**Comment by stevenzhou0825** [comment]
哦，知道了，5.0之后说原生支持pac，可添加了还不能用，IOS都可以，谢谢您

**Comment by Chion82** [comment]
@stevenzhou0825 不能用具体是如何？完全没有反应还是报错还是全部歌都跳过？

**Comment by wen-m** [comment]
Pac 也是只能wifi，在路由加hosts不用每个设备去改

**Comment by stevenzhou0825** [comment]
还是灰色的，点了就提示因“合作方要求，该资源暂时无法使用。”。

**Comment by Chion82** [comment]
@stevenzhou0825 那就是pac或者hosts没有设置成功。检查一下APP里面的代理设置，重启手机试试

**Comment by stevenzhou0825** [comment]
我也不清楚，我在两个android手机的设置里写了pac都没用，app中也没找到代理设置。

**Comment by Chion82** [comment]
@stevenzhou0825 刚刚试了一下，改hosts的话需要重启APP才能生效。另外你可以抓下包，看看HTTP请求的目的IP是否正确

**Comment by wen-m** [comment]
私人FM和每日推荐 没有内容，不知道是不是特例？

**Comment by Chion82** [comment]
现在应该都已经修复好了，如果再遇到问题的话请尝试切换host或者改用PAC，然后再来发issue吧

**Comment by yong1994** [comment]
安卓3.4.1只要在hosts中加多一条 103.27.77.201 ip.ws.126.net/ipquery 就可以了，亲测有效

**Comment by stevenzhou0825** [comment]
应该是,我抓包也发现了。

**Comment by Chion82** [comment]
是在境外吗？我在国内测试很多遍都没有问题

**Comment by yong1994** [comment]
是的，人在马来西亚，看来安卓版加多了一条针对国外用户的
