### ISSUE TITLE
测试付费的还是需要付费

### ISSUE THREAD

**Issue by MrBowen** [Chion82/163-music-unlock#3]
能解决地区问题已经不错啦~
作者赞~
付费问题乖乖去买会员好了~
测试歌曲：bang bang bang~

**Comment by Chion82** [comment]
现在不能直接搜索付费的歌了。能提供一下包含这首歌的歌单名吗？

**Comment by Chion82** [comment]
服务器规则已更新。现在应该可以播放付费歌曲了

**Comment by MrBowen** [comment]
一直是能播的。
但是不能下载。

**Comment by Chion82** [comment]
目前只对在线播放的API做了修改

**Comment by Chion82** [comment]
已经更新。IOS和OSX客户端已经下载付费歌曲了。安卓客户端由于需要校验文件md5（目前接口无法获取到歌曲文件md5），付费歌曲最后会下载失败

**Comment by MrBowen** [comment]
谢谢回复&跟进。

收到邮件提醒的第一时间就尝试了下载（野子 live & Bang Bang Bang）。
手机网络 & 学校网络均失败。
到家后又尝试了家中的无线网络，依然失败。
从旧 hosts 切换到新 hosts 问题依旧。

PS.
在你这次更新前，下载提示歌曲需付费。
修改后，提示正在计算小，后为下载失败，网络异常。

**Comment by MrBowen** [comment]
Update：
OS X 端，同没有速度。

PING 108.61.201.11 (108.61.201.11): 56 data bytes
64 bytes from 108.61.201.11: icmp_seq=0 ttl=50 time=329.923 ms
64 bytes from 108.61.201.11: icmp_seq=1 ttl=50 time=348.060 ms

PING 103.27.77.201 (103.27.77.201): 56 data bytes
64 bytes from 103.27.77.201: icmp_seq=0 ttl=51 time=293.880 ms
64 bytes from 103.27.77.201: icmp_seq=1 ttl=51 time=258.834 ms
64 bytes from 103.27.77.201: icmp_seq=2 ttl=51 time=258.877 ms

**Comment by Chion82** [comment]
能提供一下包含这个歌曲的歌单名么

**Comment by Chion82** [comment]
试了一下，IOS客户端是可以下载的
安卓客户端提示网络异常是因为无法验证文件，目前还无法解决
![image](https://cloud.githubusercontent.com/assets/6501930/14337756/4750780e-fca3-11e5-99c1-fe6a57202b85.png)

**Comment by Chion82** [comment]
测试了一下，OSX客户端也可以下载。请检查`m1.music.126.net`, `m2.music.126.net`, `m3.music.126.net`是否被当地DNS解析成了`1.1.1.1`。m1~m3都是存放音乐文件的CDN，都是一样的。这里提供几个可用的ip，可以加到hosts里面:
```
118.118.171.29
182.140.231.59
182.140.147.56
61.188.191.90
```
<img width="542" alt="screen shot 2016-04-07 at 12 47 49 pm" src="https://cloud.githubusercontent.com/assets/6501930/14340934/049b876c-fcbf-11e5-9b87-9d2b04573423.png">

**Comment by MrBowen** [comment]
真正 close 了。
实测：
ping m1.music.126.net                                                 146 ↵
PING n2.panthercdn.com (151.249.88.207): 56 data bytes
64 bytes from 151.249.88.207: icmp_seq=0 ttl=55 time=10.899 ms

ping m2.music.126.net                                                 146 ↵
PING m2.music.126.net.wscdns.com (1.1.1.1): 56 data bytes
Request timeout for icmp_seq 0

ping m3.music.126.net                                                 146 ↵
PING oversea.video.speedcdns.com (203.130.58.29): 56 data bytes
64 bytes from 203.130.58.29: icmp_seq=0 ttl=56 time=10.197 ms

给 m2 添加了 hosts，现在正常了。
非常感谢。

**Comment by MrBowen** [comment]
Update:
今天去换了手机。
重新部署了 surge 配置。
发现已经不能下载了。
还是这两首，其它可以测试 Taloy 的。

**Comment by Chion82** [comment]
现在再试试呢？

**Comment by MrBowen** [comment]
目前配置如下

music.163.com = 103.27.77.201
m2.music.126.net = 61.188.191.90

m1 和 m3 返回：
151.249.88.174
203.130.58.29

**Comment by Chion82** [comment]
你的m1的ip是美国ip，网易的国外镜像可能没有版权歌曲，试试将m1~m3都设置为上述几个国内镜像的IP试试？

**Comment by MrBowen** [comment]
OK…… Close……
再次感谢！~
