### ISSUE TITLE
说一个可以收藏的方法

### ISSUE THREAD

**Issue by qq316107934** [Chion82/163-music-unlock#4]
点击下载，然后选择一个歌单，再把下载文件删除，就躺在歌单里了。亲测有效。

**Comment by Chion82** [comment]
还有这奇怪的方法...感谢分享，稍后更新到README中

**Comment by xiajinchun** [comment]
只能播放啊，收藏和下载都不行，比如Shake it off - Taylor Swift，收藏和下载都会弹出`当前资源须付费使用`，6S＋Surge1.2

**Comment by Chion82** [comment]
@xiajinchun 付费歌曲不能直接添加到自己的歌单里面。可以直接收藏包含这首歌的歌单，然后再下载就可以了

**Comment by xiajinchun** [comment]
就是说只能放到收藏的歌单里面嘛，不能放在自己创建的歌单里面？

**Comment by Chion82** [comment]
@xiajinchun 是的

**Comment by xiajinchun** [comment]
不错，下载了放到iTunes里面 也还是可以，哈哈 👍
