### ISSUE TITLE
iOS客户端点别人头像显示不了别人资料和歌单了

### ISSUE THREAD

**Issue by ganhang** [Chion82/163-music-unlock#7]
如题

**Comment by TomatoFryEggs** [comment]
同样问题

**Comment by Chion82** [comment]
查看用户资料和歌单的接口用的是https的API，由于客户端会验证SSL证书，改host后https请求会失败。目前还没有解决方案

**Comment by Chion82** [comment]
如果可以在设备上使用PAC或者类似iptables的方法，将目的端口为80的请求DNAT到反代服务器，443的请求RETURN的话应该可以解决

**Comment by Chion82** [comment]
已修复。在服务器上用iptables直接转发443包即可
